import express from 'express';
import cors from 'cors';
import path from 'path';
import { fileURLToPath } from 'url';
import { GoogleGenAI, Type } from "@google/genai";

// Configure Environment
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
app.use(cors());
app.use(express.json());

// Initialize Gemini (Ensure process.env.API_KEY is set in Hostinger Environment Variables)
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });

// Build Memory Store
let BUILD_MEMORY = {
  buildId: "AF-ENT-NODE-001",
  version: "2.2.0-STABLE",
  primaryColor: "#007bff",
  navigationTree: ["Dashboard", "Transactions", "Customers", "Communication", "Staff", "Reports", "Miscellaneous"],
  mandatoryModules: ["TemplateArchitect", "DualColumnLedger", "ExtendedCustomerProfile", "RiskGradingEngine"],
  coreDesignElements: ["BlueHeroHeader", "SideBarHierarchy", "ModalForms", "GeminiAiStrategist"],
  lastUpdate: new Date().toISOString(),
  serverNode: "139.59.10.70"
};

// --- API ROUTES ---

// 1. Memory Sync
app.get('/api/system/memory', (req, res) => {
  res.json(BUILD_MEMORY);
});

app.post('/api/system/memory/commit', (req, res) => {
  BUILD_MEMORY = { ...BUILD_MEMORY, ...req.body, lastUpdate: new Date().toISOString() };
  res.json({ status: "committed", memory: BUILD_MEMORY });
});

// 2. Meta Infrastructure Proxy (Mock)
app.get('/api/infrastructure/templates', async (req, res) => {
  const synced = [
    { id: 'tpl_1', name: 'AURAGOLD_ORDER_CONFIRMATION', content: 'Order confirmed for {{1}}.', category: 'UTILITY', status: 'synced' },
    { id: 'tpl_2', name: 'AURAGOLD_PAYMENT_REQUEST', content: 'Payment due for {{1}} of {{2}}.', category: 'UTILITY', status: 'synced' }
  ];
  res.json(synced);
});

// 3. Gemini Recovery Orchestrator
app.post('/api/ai/strategy', async (req, res) => {
  const { customer } = req.body;
  if (!process.env.API_KEY) {
     res.status(500).json({ error: 'API_KEY missing on server' });
     return;
  }
  try {
    const result = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Generate recovery strategy for ${customer.name} with balance ${customer.currentBalance}.`,
      config: { responseMimeType: "application/json" }
    });
    if (result.text) res.json(JSON.parse(result.text));
    else res.status(500).json({ error: 'AI Timeout' });
  } catch (err) {
    console.error("AI Error:", err);
    res.status(500).json({ error: 'Analysis Failed' });
  }
});

// --- PRODUCTION SERVING ---

// Serve static files from the 'dist' directory (generated by 'npm run build')
app.use(express.static(path.join(__dirname, 'dist')));

// Handle React Routing (SPA): Return index.html for any unknown route
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

// Start Server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`[ArrearsFlow] Kernel Active on Node 139.59.10.70`);
  console.log(`[ArrearsFlow] Listening on port ${PORT}`);
});
